### ISSUE TITLE
AD issues causing website to go down aswell

### ISSUE THREAD

**Issue by fkul** [Bitmapped/UmbBackofficeMembershipProvider#7]
We are successfully using this plugin in production environment. Recently we had some issues with the Active Directory server and unfortunately this caused our website to go offline with the exception "Unable to establish secure connection with the server".
Is there a way to avoid website issues when the Active Directory server goes down? I imagine that this should only stop the backoffice from working.

**Comment by Bitmapped** [comment]
As far as I know, the only time Umbraco should be calling this plugin is to validate a login to the backoffice. I don't believe it would be calling anytime else.

I'd look at the web.config file and make sure you're not using AD in some fashion for Members. Also, you might look at how you're connecting to your SQL server and to your file storage, if not stored on the same web server, to make sure the AD outage didn't cause problems there.

I'm going to close this issue because I don't think it's anything related to this plugin, and if it is, it's an architectural issue with Umbraco and not something under this plugin's control.
